Fix Invalid shipping type informed
PHPSC/pagseguro pull request #57
Opened 2017-10-26 15:01 UTC by dlimars

Quando é efetuada uma venda digitada, ou algum pagamento que não possua frete, ao utilizar o `Locator` é disparado uma excessão `Invalid shipping type informed`, o que não deveria ocorrer, pois de fato, não existe dados de envio.

um exemplo de XML retornado pelo Pagseguro:
```
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<transaction>
	<date>2017-10-09T18:00:26.000-03:00</date>
	<code>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</code>
	<type>1</type>
	<status>3</status>
	<lastEventDate>2017-10-09T18:00:36.000-03:00</lastEventDate>
	<paymentMethod>
		<type>1</type>
		<code>107</code>
	</paymentMethod>
	<grossAmount>219.80</grossAmount>
	<discountAmount>0.00</discountAmount>
	<feeAmount>19.37</feeAmount>
	<netAmount>200.43</netAmount>
	<extraAmount>0.00</extraAmount>
	<escrowEndDate>2017-11-08T19:00:26.000-02:00</escrowEndDate>
	<installmentCount>2</installmentCount>
	<itemCount>1</itemCount>
	<items>
		<item>
			<id>1</id>
			<description>Venda digitada</description>
			<quantity>1</quantity>
			<amount>219.80</amount>
		</item>
	</items>
</transaction>```

2017-10-26 17:11 UTC, sergiors commented
@dlimars conseguiria fazer um teste com esse XML de resposta?
Eu nao estou interado, mas talvez o @lcobucci possa ajudar nisso.

2018-05-05 20:54 UTC, lcobucci commented
@dlimars mil perdões pela minha demora eterna em revisar seu PR.

2018-05-05 20:58 UTC, lcobucci requested changes
Sua mudança faz muito sentido, porém você poderia adicionar um teste de unidade que cubra este cenário?

2019-12-06 12:59 UTC, cassiosantos commented
@dlimars  muito obrigado pela sua contribuição!

Infelizmente, como este PR é de 2017 e não tem atualizações desde 2018, vou encerá-lo.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.

2019-12-06 12:59 UTC, closed without merging