Checkout de Serviços
PHPSC/pagseguro pull request #63
Opened 2018-05-05 20:07 UTC by lmarttins

- Possibilidade de setar o atributo "shippingAddressRequired" para que os dados de endereço são sejam obrigatórios.

[](https://dev.pagseguro.uol.com.br/documentacao/pagamento-online/pagamentos/checkout-de-servico)

2018-05-05 20:42 UTC, lcobucci requested changes

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/CheckoutBuilder.php
> +     * @param string $shippingAddressRequired
Você tá testando tudo usando `true|false`, assim isto deveria ser `boolean`.

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/CheckoutBuilder.php
> +    public function setShippingAddressRequired($shippingAddressRequired);
Eu sei que tudo nessa classe tá com setters, mas talvez ter o método `requireShippingAddress()` faça mais sentido - talvez até ter o outro método com o oposto.

Isto encapsula o comportamento do builder, torna a interface do builder um pouco mais fluente e diminui a possibilidade te passar coisas bizarras como parâmetro (já que esta lib suporta PHP 5).

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/Checkout/Order.php
> +     * @Serializer\XmlElement(cdata=false)
Tá faltando um `@Serializer\Type("boolean")` pra garantir que a gente sempre trabalhe com o tipo correto.

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/Checkout/Order.php
> +     * @return string
Deveria ser boolean

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/Checkout/Order.php
> +    public function getShippingAddressRequired()
`isShippingAddressRequired()` faz mais sentido já que a propriedade é (deveria ser) boolean.

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/Checkout/Order.php
> +     * @var string
`boolean`

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/Checkout/Order.php
> +    public function setShippingAddressRequired($shippingAddressRequired)
Mesmo comentário sobre encapsulamento aqui.

2018-05-05 20:42 UTC, lcobucci commented on src/Requests/Checkout/Order.php
> +    private $shippingAddressRequired;
Isto deveria ser `false` por padrão?

2018-05-05 22:43 UTC, lmarttins reviewed
Refatorando conforme as sugestões

2018-05-05 22:43 UTC, lmarttins commented on src/Requests/Checkout/Order.php
> +    private $shippingAddressRequired;
De fato não, segue a alteração.

2018-05-06 07:22 UTC, lcobucci requested changes
Tá ficando ótimo, só mais umas coisinhas. Acho que seria interessante também colocar um teste pra ver como fica a serialização XML, exemplo:

https://github.com/PHPSC/pagseguro/blob/facd04385823a14043d77bfb2140ae63ffb7530b/tests/Requests/Checkout/CheckoutTest.php#L168-L216

2018-05-06 12:53 UTC, lmarttins commented on src/Requests/Checkout/Order.php
> +    private $shippingAddressRequired;
Perfeito, vc tem razão.

2018-05-06 12:59 UTC, lmarttins commented on src/Requests/Checkout/Order.php
> +        return $this->shippingAddressRequired;
Será criado um teste para cobrir este cenário.

2018-05-06 13:32 UTC, lmarttins reviewed
- Configurando o atributo shippingAddressRequired com valor padrão true.
- Teste para cobrir o cenário para garantir que o atributo shippingAddressRequired esteja configurado com o valor padrão true.

2018-05-06 22:26 UTC, lcobucci requested changes
@lmarttins últimos detalhes pra ficar 100%, muito obrigado pela força 😄

2018-05-06 22:26 UTC, lcobucci commented on src/Requests/Checkout/Order.php
> +     * @Serializer\XmlElement(cdata=true)
Acredito que como o valor é `boolean` não faça sentido a gente ter `cdata=true` nesta annotation.

2018-05-06 22:26 UTC, lcobucci commented on README.md
> +...
Coloque as reticências como comentário, por favor. Caso alguém copie o código não terá erro de sintaxe 😄

2018-05-06 22:26 UTC, lcobucci commented on README.md
> +Este código realiza o checkout como serviço, sem a necessidade dos dados de endereço:
Talvez assim fique um pouco mais descritivo:

```diff
- Este código realiza o checkout como serviço, sem a necessidade dos dados de endereço:
+ Caso você queria enviar os dados de checkout sem requerir o endereço de entrega, você
+ pode utilizar o método `CheckoutBuilder#withoutShippingAddress()`. Por exemplo:
```

2018-05-06 22:39 UTC, lmarttins commented on README.md
> +...
Até pensei nisso, mais acabei adicionando as reticências rs

2018-05-07 21:25 UTC, lcobucci requested changes

2018-05-07 21:25 UTC, lcobucci commented on tests/Purchases/Transactions/xml/transactionWithoutShipping.xml
> +</transaction>
Falta quebra de linha

2018-05-07 21:25 UTC, lcobucci commented on tests/Purchases/Transactions/DecoderTest.php
> +        $decoder = new Decoder;
Parênteses aqui também

2018-05-07 21:25 UTC, lcobucci commented on tests/Purchases/Transactions/DecoderTest.php
> +        $obj = simplexml_load_file(__DIR__.'/xml/transactionWithoutShipping.xml');
Faltando espaço antes e depois do ponto.

2018-05-07 21:26 UTC, lcobucci commented
@lmarttins você conseguiria reorganizar seu branch usando rebase? O histórico de commits poderia ficar um pouco mais organizado pra ser integrado ao `master` =)

2019-12-06 13:00 UTC, cassiosantos commented
@lmarttins  muito obrigado pela sua contribuição!

Infelizmente, como este PR não é atualizado desde 2018, vou encerá-lo.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.

2019-12-06 13:00 UTC, closed without merging