Adicionando grumphp para rodar o PHPCS e o PHPUnit antes do commit
PHPSC/pagseguro pull request #64
Opened 2018-05-11 03:25 UTC by viniciusalonso

Lendo as PR's antigas notei que as verificações dos padrões de código seguindo a PSR2 estavam sendo feitas de forma manual.

Adicionei a lib grumphp e configurei para que toda vez que o desenvolvedor tente comitar, seja verificado o padrão do código e também sejam rodados os testes.

2018-05-11 04:35 UTC, mrprompt approved these changes
show de bola!

2018-05-11 07:07 UTC, lcobucci requested changes

2018-05-11 07:07 UTC, lcobucci commented on grumphp.yml
> +            standard: PSR2
Seria melhor a gente ter um `phpcs.xml.dist` pra definir as configurações do PHPCS ao inves de ter os parâmetros aqui.

2018-05-11 12:25 UTC, viniciusalonso commented on grumphp.yml
> +            standard: PSR2
Quer adicionar mais verificações além do PSR2?

2018-05-11 13:59 UTC, sergiors commented
Acho que o projeto não precisa do `composer.lock`, já que não é o main project

2019-12-06 13:04 UTC, cassiosantos commented
@viniciusalonso muito obrigado pela sua contribuição!

Infelizmente, como este PR não tem atualizações desde 2018, vou encerá-lo.

Devido a falta de disponibilidade dos colaboradores também estamos descontinuando este projeto.

Nos vemos nos próximos eventos. É sempre muito bom te encontrar!

2019-12-06 13:04 UTC, closed without merging